# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 213de7d1c24f00becd9262ae8a8363f1fec6a33d8c71664da65890309b53f35b6d2058ad326edac5aba07da53db46143c039443fd7cce63f8e61916f3d0cecc8

test:
  secret_key_base: c1b87a05c8f7de3d4b056f1c4da95fb9918cef33f5210c5a58760722874da2815da19c12099a8c8a9946b31c97b86c887080c3d2206a72a97e5f379ac94572ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
